# remap prefix from 'C-b' to 'C-n'
unbind C-b
set-option -g prefix C-n
bind-key C-n send-prefix

# start window index at 1
set -g base-index 1
set -g pane-base-index 1

# Enable scroll
setw -g mouse on

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# kill all other sessions
bind-key K run-shell 'tmux kill-session -a -t $(tmux display-message -p "#{session_name}")'

# Open menu
set -g @menus_trigger 'm'

# New window with default path set to current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @plugin 'jaclu/tmux-menus' # See https://github.com/jaclu/tmux-menus
set -g @plugin 'AngryMorrocoy/tmux-neolazygit' # See https://github.com/AngryMorrocoy/tmux-neolazygit
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name' # See https://github.com/joshmedeski/tmux-nerd-font-window-name

# Lazygit config
set -g @open-lazygit 'g'

# catppuccin styling
# General statusline customisation
set -g status-style 'bg=terminal'

# Theme
## Configure the catppuccin plugin <https://github.com/catppuccin/tmux>
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'

set -g status-position top

# status left style
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_mantle},bold]  #S },#{#[bg=#{@thm_mantle},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# set -g status-justify "left"

# status right style
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#{?#{e|>=:10,#{battery_percentage}},#{#[bg=#{@thm_red},fg=#{@thm_mantle}]},#{#[bg=#{@thm_mantle},fg=#{@thm_pink}]}} #{battery_icon} #{battery_percentage} "
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#{@thm_mantle}]#{?#{==:#{online_status},ok},#[fg=#{@thm_mauve}] 󰖩 on ,#[fg=#{@thm_red},bold]#[reverse] 󰖪 off }"
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# window style
set -wg automatic-rename on
set -g automatic-rename-format ''
set -g window-status-separator '|'
set -g status-justify 'absolute-centre'
set -g @catppuccin_window_status_style 'custom'
set -g @catppuccin_window_flags ""
set -g @catppuccin_window_number ""
set -g @catppuccin_window_text "#[fg=#{@thm_rosewater},bg=#{@thm_mantle}] #I#{?#{!=:#{window_name},},: #W ,}"
set -g @catppuccin_window_current_number ""
set -g @catppuccin_window_current_text "#[fg=#{@thm_mantle},bg=#{@thm_peach}] #I#{?#{!=:#{window_name},},: #W ,}"

# Configure Online
set -g @online_icon "ok"
set -g @offline_icon "nok"

run '~/.tmux/plugins/tpm/tpm'
